name: Build and Push AVM Mirror

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image to ACR
      run: |
        az acr build \
          --registry avmmodulesbc \
          --image avm-mirror:latest \
          --file Dockerfile \
          https://github.com/${{ github.repository }}.git
